[build]
builder = "NIXPACKS"

[deploy]
startCommand = "dotnet Server.dll"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
ASPNETCORE_ENVIRONMENT = "Railway"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT" 