// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Database;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(JustClimbDbContext))]
    partial class JustClimbDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<string>("BestClearTimesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("best_clear_times_json");

                    b.Property<string>("BestDeathCountsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("best_death_counts_json");

                    b.Property<string>("BestGemRewardsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("best_gem_rewards_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentDeathCountsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("current_death_counts_json");

                    b.Property<string>("CurrentPlayTimesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("current_play_times_json");

                    b.Property<int>("Gems")
                        .HasColumnType("int")
                        .HasColumnName("gems");

                    b.Property<int>("Gold")
                        .HasColumnType("int")
                        .HasColumnName("gold");

                    b.Property<string>("SelectedCharacter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("selected_character");

                    b.Property<string>("StageClearsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stage_clears_json");

                    b.Property<string>("StageFlagPositionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stage_flag_positions_json");

                    b.Property<string>("SteamAvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("steam_avatar_url");

                    b.Property<string>("SteamDisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("steam_display_name");

                    b.Property<bool>("TutorialDisplayed")
                        .HasColumnType("bit")
                        .HasColumnName("tutorial_displayed");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Server.Models.UserItem", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("user_id");

                    b.Property<string>("ItemId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("item_id");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("count");

                    b.HasKey("UserId", "ItemId");

                    b.ToTable("user_items", (string)null);
                });

            modelBuilder.Entity("Server.Models.UserStageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("BestClearTime")
                        .HasColumnType("real")
                        .HasColumnName("best_clear_time");

                    b.Property<int>("BestDeathCount")
                        .HasColumnType("int")
                        .HasColumnName("best_death_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("display_name");

                    b.Property<int>("StageNumber")
                        .HasColumnType("int")
                        .HasColumnName("stage_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StageNumber", "BestClearTime")
                        .HasDatabaseName("IX_UserStageRecords_StageNumber_BestClearTime");

                    b.HasIndex("StageNumber", "BestDeathCount")
                        .HasDatabaseName("IX_UserStageRecords_StageNumber_BestDeathCount");

                    b.HasIndex("UserId", "StageNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_UserStageRecords_UserId_StageNumber");

                    b.ToTable("user_stage_records", (string)null);
                });

            modelBuilder.Entity("Server.Models.UserItem", b =>
                {
                    b.HasOne("Server.Models.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
