// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Database;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(JustClimbDbContext))]
    partial class JustClimbDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.Achievement", b =>
                {
                    b.Property<int>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("achievement_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AchievementId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("RewardAmount")
                        .HasColumnType("int")
                        .HasColumnName("reward_amount");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("reward_type");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("AchievementId");

                    b.HasIndex("Category");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("achievements", (string)null);
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("Gems")
                        .HasColumnType("int")
                        .HasColumnName("gems");

                    b.Property<int>("Gold")
                        .HasColumnType("int")
                        .HasColumnName("gold");

                    b.Property<string>("SelectedCharacter")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("selected_character");

                    b.Property<string>("SteamAvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("steam_avatar_url");

                    b.Property<string>("SteamDisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("steam_display_name");

                    b.Property<bool>("TutorialDisplayed")
                        .HasColumnType("bit")
                        .HasColumnName("tutorial_displayed");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Server.Models.UserAchievement", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_id");

                    b.Property<int>("AchievementId")
                        .HasColumnType("int")
                        .HasColumnName("achievement_id");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("claimed_at");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("unlocked_at");

                    b.HasKey("UserId", "AchievementId");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UnlockedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ClaimedAt")
                        .HasDatabaseName("IX_UserAchievements_Unclaimed")
                        .HasFilter("claimed_at IS NULL");

                    b.ToTable("user_achievements", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserAchievements_ClaimedAfterUnlock", "claimed_at IS NULL OR claimed_at >= unlocked_at");
                        });
                });

            modelBuilder.Entity("Server.Models.UserAchievementProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Chapter1PerfectStages")
                        .HasColumnType("int")
                        .HasColumnName("chapter1_perfect_stages");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("DeathsInCurrentStage")
                        .HasColumnType("int")
                        .HasColumnName("deaths_in_current_stage");

                    b.Property<string>("ItemTypesUsedJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("item_types_used_json");

                    b.Property<int>("ItemsPurchased")
                        .HasColumnType("int")
                        .HasColumnName("items_purchased");

                    b.Property<int>("PerfectClears")
                        .HasColumnType("int")
                        .HasColumnName("perfect_clears");

                    b.Property<int>("SpeedClears")
                        .HasColumnType("int")
                        .HasColumnName("speed_clears");

                    b.Property<int>("StagesCompleted")
                        .HasColumnType("int")
                        .HasColumnName("stages_completed");

                    b.Property<string>("UnlockedCharactersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unlocked_characters_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UsedItemInCurrentStage")
                        .HasColumnType("bit")
                        .HasColumnName("used_item_in_current_stage");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_achievement_progress", (string)null);
                });

            modelBuilder.Entity("Server.Models.UserItem", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_id");

                    b.Property<string>("ItemId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("item_id");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("count");

                    b.HasKey("UserId", "ItemId");

                    b.ToTable("user_items", (string)null);
                });

            modelBuilder.Entity("Server.Models.UserStageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("BestClearTime")
                        .HasColumnType("real")
                        .HasColumnName("best_clear_time");

                    b.Property<int>("BestDeathCount")
                        .HasColumnType("int")
                        .HasColumnName("best_death_count");

                    b.Property<int>("BestGemCount")
                        .HasColumnType("int")
                        .HasColumnName("best_gem_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentDeathCount")
                        .HasColumnType("int")
                        .HasColumnName("current_death_count");

                    b.Property<float>("CurrentPlayTime")
                        .HasColumnType("real")
                        .HasColumnName("current_play_time");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("display_name");

                    b.Property<float?>("FlagX")
                        .HasColumnType("real")
                        .HasColumnName("flag_x");

                    b.Property<float?>("FlagY")
                        .HasColumnType("real")
                        .HasColumnName("flag_y");

                    b.Property<float?>("FlagZ")
                        .HasColumnType("real")
                        .HasColumnName("flag_z");

                    b.Property<bool>("IsCleared")
                        .HasColumnType("bit")
                        .HasColumnName("is_cleared");

                    b.Property<int>("StageNumber")
                        .HasColumnType("int")
                        .HasColumnName("stage_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StageNumber", "BestClearTime");

                    b.HasIndex("StageNumber", "BestDeathCount");

                    b.HasIndex("UserId", "StageNumber")
                        .IsUnique();

                    b.ToTable("user_stage_records", (string)null);
                });

            modelBuilder.Entity("Server.Models.UserAchievement", b =>
                {
                    b.HasOne("Server.Models.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.User", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.UserAchievementProgress", b =>
                {
                    b.HasOne("Server.Models.User", "User")
                        .WithOne("AchievementProgress")
                        .HasForeignKey("Server.Models.UserAchievementProgress", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.UserItem", b =>
                {
                    b.HasOne("Server.Models.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.UserStageRecord", b =>
                {
                    b.HasOne("Server.Models.User", "User")
                        .WithMany("StageRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Navigation("AchievementProgress");

                    b.Navigation("Achievements");

                    b.Navigation("Items");

                    b.Navigation("StageRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
